#!/bin/bash

# A script that will ask for a number and print out a message depending on the value. 

read -p "Enter a value: " n

case $n in
    1|2) 
        echo "One or Two";;
    [3-9]) 
        echo "It is a number between Three and Nine";;
    ??) 
        echo "Two characters";;
    *.txt) 
        echo "Ends in .txt";;
    *) 
        echo "Other";;
esac
    