#!/bin/bash

# Welcome to your first Bash Script

hello_message='Hello, World! :D'
current_dir=$(pwd)
readonly variable_wont_change="blue"
#variable_wont_change gets set to a read only constant that can't be changed

echo "$hello_message from $current_dir your favorite color is $variable_wont_change"