#!/bin/bash

number=2395
number2=333
number3=-4

if [ $((number % 2)) -eq 0 ];
then
   echo "The number $number is even!";
else 
   echo "The number $number is odd!"
fi

if [ $((number2 % 2)) -eq 0 ];
then 
   echo "The number $number2 is even!";
else 
   echo "The number $number2 is odd!"
fi

if [ $((number3 % 2)) -eq 0 ];
then 
   if [ $number3 -gt 0 ];
      then 
         echo "The number $number3 is even!";
      else 
         echo "The number $number3 is odd!"
      fi
else 
   echo "The number $number3 is odd!"
fi